import { createContext } from 'react'
interface IUserData {
    uid:string
    userPos:any
    name:any
    nickname:any
    cpf:any
    height:any
    cep:any
    city:any
    emergencyContact:any
    initialDate:any
    address:any
    cityState:any
    scope:any
    maritalStatus:any
    github:any
    paymentModel:any
    birthDate:any
    emergencyName:any
    issuingBody:any
    kinship:any
    weight:any
    rg:any
    shippingDate:any
    personalPhone:any
    amountCharged:any
    bankNumber:any
    accountNumber:any
    agency:any
    listStatusForFilter:any
    listSellersForFilter:any
    device:any
}
export const userContext = createContext<IUserData>(({uid:null,
    userPos:null,
    name:null,
    nickname:null,
    cpf:null,
    height:null,
    cep:null,
    city:null,
    emergencyContact:null,
    initialDate:null,
    address:null,
    cityState:null,
    scope:null,
    maritalStatus:null,
    github:null,
    paymentModel:null,
    birthDate:null,
    emergencyName:null,
    issuingBody:null,
    kinship:null,
    weight:null,
    rg:null,
    shippingDate:null,
    personalPhone:null,
    amountCharged:null,
    bankNumber:null,
    accountNumber:null,
    agency:null,
    listStatusForFilter:null,
    listSellersForFilter:null,
    device:null}))
